spring:
  application:
    name: Incident-Management
  datasource:
    url: jdbc:mysql://localhost:3306/incident_management
    username: root
    password: jai9
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

google:
  api:
    key: AIzaSyCVQZFvovAlMW2ligkP9UmARoeeLwLrr8o
